version: '3.8'

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgres
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: SuperSecretPassword
      POSTGRES_DB: db
    ports: 
      - '5433:5432'
volumes:
  postgres_data: